// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class MoldPart
    {
        [Key]
        public int MoldPartId { get; set; }
        [Required]
        [StringLength(12)]
        public string MoldPartCode { get; set; }
        public int MoldId { get; set; }
        public int BomDetailId { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(BomDetailId))]
        [InverseProperty("MoldPart")]
        public virtual BomDetail BomDetail { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.MoldPart))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [ForeignKey(nameof(MoldId))]
        [InverseProperty("MoldPart")]
        public virtual Mold Mold { get; set; }
    }
}